### ISSUE TITLE
 error: unknown type name ‘uint64_t’

### ISSUE THREAD

**Issue by jiangcuo** [DualCoder/vgpu_unlock#52]
Building module:
cleaning build area...
'make' -j12 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.4.114-1-pve IGNORE_CC_MISMATCH='' modules.....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.4.114-1-pve (x86_64)
Consult /var/lib/dkms/nvidia/460.73.02/build/make.log for more information.

//
/opt/vgpu_unlock/vgpu_unlock_hooks.c:1173:35: error: unknown type name ‘uint64_t’
/opt/vgpu_unlock/vgpu_unlock_hooks.c:791:17: warning: ‘vgpu_unlock_bar3_end’ defined but not used [-Wunused-variable]
 static uint64_t vgpu_unlock_bar3_end;

**Comment by DualCoder** [comment]
> /opt/vgpu_unlock/vgpu_unlock_hooks.c:1173:35: error: unknown type name ‘uint64_t’

Please double check the order of the `#include` lines. From the README:

> Modify the file /usr/src/nvidia-<version>/nvidia/os-interface.c and add the following line **after the lines begining with #include** at the beginning of the file.
>
> `#include "<path_to_vgpu_unlock>/vgpu_unlock_hooks.c"`

I.e the added line should be after the existing lines beginning with `#include`.

> /opt/vgpu_unlock/vgpu_unlock_hooks.c:791:17: warning: ‘vgpu_unlock_bar3_end’ defined but not used [-Wunused-variable]
> static uint64_t vgpu_unlock_bar3_end;

I suspect this warning is a consequence of the error above.

**Comment by jiangcuo** [comment]
thanks.

```
 * _NVRM_COPYRIGHT_END_
 */

#define  __NO_VERSION__
#include "nv-misc.h"
#include "os-interface.h"
#include "nv-linux.h"
#include "nv-time.h"
#include "/opt/vgpu_unlock/vgpu_unlock_hooks.c"
```

it's working
